### ISSUE TITLE
Lesbian Painting

### ISSUE THREAD

**Issue by SpacEagle17** [Pridecraft-Studios/pridepack#12]
I would like to suggest making one of the 2x2 paintings a lesbian painting to further complete the paintings collection

**Comment by Nu-Git** [comment]
Added! https://github.com/Pridecraft-Studios/pridepack/blob/5e22430c0d49479fa9078a76bda2fce89b0a2f2d/assets/minecraft/textures/painting/skeleton.png
![skeleton](https://github.com/Pridecraft-Studios/pridepack/assets/124838505/fb20e5ea-61cd-491d-afb0-9f3591092b31)

I have also added a genderqueer one in
![alban](https://github.com/Pridecraft-Studios/pridepack/assets/124838505/0a9e9939-23c8-4435-8c0e-311898275666)
 the same commit.
