### ISSUE TITLE
Add pride candles

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/pridepack#14]
(5.1) Modify Candle textures to be themed with Pride flags.
The colors should be themed the same as the beds.
This should also be applied to [Pride Bones](https://github.com/pridecraft-studios/pridebones) and [Faithful Pride](https://github.com/pridecraft-studios/faitfulpride).

**Comment by exhq** [comment]
https://github.com/Pridecraft-Studios/pridepack/commit/49c129a3b8b1e06069e7275f0ee86f2126e169d0
