### ISSUE TITLE
Add Pride Frogs

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/pridepack#15]
We should theme the Frong. These should be recreated for [Pride Bones](https://github.com/pridecraft-studios/pridebones) and [Faithful Pride](https://github.com/pridecraft-studios/faitfulpride)

**Comment by worldwidepixel** [comment]
I've had frog textures made for quite a while now. What are you specifically looking for with the frogs' design? This would be a lot easier with more creative direction. The textures are below:
![image](https://github.com/Pridecraft-Studios/pridepack/assets/58098422/746a993b-13db-4622-89e5-5a5d75b6b19a)
![image](https://github.com/Pridecraft-Studios/pridepack/assets/58098422/80feafcd-86a1-4855-9a5d-3fd5fc03e7a7)

**Comment by worldwidepixel** [comment]
> Shall I make a pull request?

**Comment by blryface** [comment]
yeah, sure

**Comment by worldwidepixel** [comment]
> yeah, sure

https://github.com/Pridecraft-Studios/pridepack/pull/40

**Comment by blryface** [comment]
Canceled
