### ISSUE TITLE
Add pride Axolotls

### ISSUE THREAD

**Issue by Avery-Rose** [Pridecraft-Studios/pridepack#2]
Add pride themed axolotls

**Comment by Nu-Git** [comment]
elaborate, please

**Comment by Avery-Rose** [comment]
just like the bees, have pride flags for axolotl.

**Comment by Nu-Git** [comment]
Oh sure, we're gonna make axolotls be pride flags on v4.20, based off the new @sakecode beds. (Yellow Intersex, Blue MLM etc)

**Comment by Nu-Git** [comment]
I'm gonna try and add MAVM compatibility for even more axolotls too.

**Comment by Nu-Git** [comment]
This is going to be on Pridemod using the [MAVM api](https://modrinth.com/mod/mavapi).

**Comment by blryface** [comment]
This is now getting added to Pridepack 5.1

**Comment by NormalFery** [comment]
This has been added for the release of Pridepack 5.1 already

**Comment by blryface** [comment]
> I'm gonna try and add MAVM compatibility for even more axolotls too.

Well that surely happened
