### ISSUE TITLE
Add pride elytras

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/pridepack#21]
This will only be seen by people not wearing a cape, but we should theme the vanilla no-cape elytra.

**Comment by LaylaMeower** [comment]
maybe we should also implement an addon that gays out the capes themselves?

**Comment by blryface** [comment]
that's impossible without mods. And, either way, it would probably be best if the person modifying their cape did it themselves as there are many mods that let you use custom capes already

**Comment by blryface** [comment]
Added in [this commit](https://github.com/Pridecraft-Studios/pridepack/commit/e6c6aa70aba10dd5372af456f0c4c525ce9cfff4)
