### ISSUE TITLE
Add pride capes

### ISSUE THREAD

**Issue by LaylaMeower** [Pridecraft-Studios/pridepack#22]

**Comment by Gaming32** [comment]
This is impossible to do in a resourcepack. Might be better for [PrideMod](https://github.com/Pridecraft-Studios/PrideMod).

**Comment by LaylaMeower** [comment]
> This is impossible to do in a resourcepack. Might be better for [PrideMod](https://github.com/Pridecraft-Studios/PrideMod).

Oh, right. Forgot about that.
