### ISSUE TITLE
Re-do the Cocoa Lesbeans texture

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/pridepack#29]

**Comment by NormalFery** [comment]
![cocoa_stage2](https://github.com/Pridecraft-Studios/pridepack/assets/132052650/05ac5946-f89e-42d6-9f5d-8d2bb89871b2)
![cocoa_stage1](https://github.com/Pridecraft-Studios/pridepack/assets/132052650/ce27a76b-fc44-45eb-978c-e07ec4ee13c6)
![cocoa_stage0](https://github.com/Pridecraft-Studios/pridepack/assets/132052650/0b2a3329-c311-4fd9-92e2-84bf4d53dbb6)
I think these ones are the best, please check tho :3
