### ISSUE TITLE
SUGGESTION: Edit inventory.png and all other GUIs, and maybe make a dark theme version of pridepack?

### ISSUE THREAD

**Issue by NormalFery** [Pridecraft-Studios/pridepack#37]
Maybe edit all guis in the pack to make it so that the GUI could be theme, along with adding a dark mode version. It could be something like [DefaultDarkMode](https://modrinth.com/resourcepack/default-dark-mode), except changed slightly, and maybe with progress flag stripes in an inventory corner

**Comment by blryface** [comment]
Our resource pack is still compatible with any UI pack you put over it, some people surprisingly don't like Dark Mode. We can make a separate pack, like PrideGUI, so people still have the option to choose whether to have or not a GUI modification

**Comment by NormalFery** [comment]
True, we could do it like that, maybe the normal/light mode version for default pridepack and PrideGUI for dark mode? The gui changes for pridepack default/light could be just the progress frag stripe in a corner, definitively easier.

**Comment by NormalFery** [comment]
Just checked in discord,
yeah we should just make pridepack have no gui modifications and then have PrideGUI (Dark and Light), should I start working on it later today and just... add the textures here later?

**Comment by blryface** [comment]
Sure, I'll make a new repository for PrideGUI

**Comment by NormalFery** [comment]
Great, should I close the issue or will you close it?

**Comment by LaylaMeower** [comment]
For god's sake, @blryface, if you've _accepted_ the suggestion to create a new pack with dark mode UI, close it as completed...

**Comment by blryface** [comment]
The birth of pridegui
