### ISSUE TITLE
XP Bar not being themed on 1.20.2+ ui

### ISSUE THREAD

**Issue by NormalFery** [Pridecraft-Studios/pridepack#38]
This is due to the 1.20.2+ changes on GUI textures, since on 1.20.2+ gui elements are split in different folders (icons.png doesn't exist anymore, it's now in the "/textures/gui/sprites/hud/" folder.

**Comment by blryface** [comment]
Correction, the pack is 1.20.3+, and those texture changes were introduced in a 1.20.3 snapshot.
I probably missed it before releasing, might give it a look when I get home. I probably will also make the texture _better_

**Comment by blryface** [comment]
i was wrong, it was on [1.20.2](https://minecraft.wiki/w/Java_Edition_1.20.2#Gameplay).
