### ISSUE TITLE
The Bumblezone compat

### ISSUE THREAD

**Issue by blryface** [Pridecraft-Studios/pridepack#45]
Theme [The Bumblezone Fabric](https://modrinth.com/mod/the-bumblezone-fabric) (and [forge](https://modrinth.com/mod/the-bumblezone-foge)) to use a simmilar style as the normal biis.

**Comment by exhq** [comment]
the mod seems to already have gay bees - will not change bee textures

**Comment by blryface** [comment]
As far as I know there are other stuff that can be themed since they follow bee colors?

**Comment by blryface** [comment]
exhq is right
