### ISSUE TITLE
Enby Flowering Azaleas

### ISSUE THREAD

**Issue by Sekalol15** [Pridecraft-Studios/pridepack#49]

**Comment by Sekalol15** [comment]
I can do some concept later

**Comment by blryface** [comment]
where concept art
also yeah I suggested we did these but sake and other people were like "no"

**Comment by blryface** [comment]
I did try a few Trans Cave vines textures, it didn't really look good

I'm yet to try flowering azaleas but cave vines aren't coming

**Comment by blryface** [comment]
Flowering azaleas are just too tiny to be able to look good
