### ISSUE TITLE
Transparent pixel on gay slimes

### ISSUE THREAD

**Issue by FifthTundraG** [Pridecraft-Studios/pridepack#55]
You can see on the texture file:
![image](https://github.com/Pridecraft-Studios/pridepack/assets/117035030/41a869cb-fad1-496e-8034-26d60853472c)
and ingame:
![2024-06-02_09 45 09_edited](https://github.com/Pridecraft-Studios/pridepack/assets/117035030/1a471945-7bd4-4928-b2f8-5999dde20257)

**Comment by blryface** [comment]
They're already getting removed in 6.0

**Comment by blryface** [comment]
Removed in recent commits
